config/routes.rb
Dogeradio::Application.routes.draw do

  root 'static_pages#main'

  get 'contact-us', to: 'static_pages#contact'
  post 'send_contact', to: 'static_pages#send_contact'
  get 'sidebar', to: 'static_pages#sidebar'
  get 'topbar', to: 'static_pages#topbar'
  get 'events_sidebar', to: 'static_pages#events_sidebar'
  get 'test', to: 'static_pages#test'
  get 'discover', to: 'static_pages#discover'
  get 'wow', to: 'static_pages#wow'
  get 'about', to: 'static_pages#about'
  get 'upload', to: 'static_pages#upload'
  post 'update_location', to: 'static_pages#update_location'
  get 'recent_tips', to: 'transactions#recent'

  post 'guest_charge', to: 'transactions#guest_charge'

  post 'sync_jambase_ids', to: 'venues#sync_jambase_ids'
  post 'search', to: 'search#search'
  get 'search_tracks', to: 'search#tracks'
  get 'search_tags', to: 'search#tags'
  get 'search_users', to: 'search#users'

  get 'local_venues', to: 'venues#local_venues'
  get 'local_events', to: 'events#local_events'
  post 'add_yelp_venues', to: 'venues#add_yelp_venues'
  get 'load_yelp_suggestions', to: "venues#load_yelp_suggestions"

  resources :venues do
    get :events, to: "events#venue_events"
    resources :events, except: [:index, :show, :destroy]
  end

	resources :events, only: [:index, :show, :destroy] do
    resources :user, only: [:new], to: 'events#new_user'
    resources :user, only: [:create], to: 'events#add_user', as: 'add_user'
  end

	resources :playlists, only: [:show] do
		post :sort
		resource :ranks
	end

  resources :tags, only: [:destroy]

  get 'top_tracks', to: "tracks#top_tracks"
	resources :tracks do
		resources :plays
		resources :tags, except: [:destroy]
		get :fond_users
		post :update_player
	end

  resources :musics, only: [:create, :new]

  devise_for :users, controllers: {registrations: "registrations"}

	post 'hold_charge', to: "transactions#hold_charge"
	resources :transactions, only: [:index]

  resources :votes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

	get 'soundcloud', to: 'users#soundcloud_auth'
	get 'soundcloud_callback', to: 'users#soundcloud_callback'
	post 'payout', to: 'users#payout'

  get 'local_users', to: 'users#local_users'
  resources :users, only: [:index]

  scope ':username' do
    post 'verify' => 'users#verify'
    post 'unverify' => 'users#unverify'
		post 'autopay' => 'users#autopay'
		post 'pay' => 'users#pay'
		post 'update_balance' => 'users#update_balance'
		get 'following' => 'users#following'
		get 'followers' => 'users#followers'
		get 'favorite_tracks'=> 'users#favorite_tracks'
	end

  get ':username', to:'users#show', as: :user

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	#skip_before_filter :verify_authenticity_token
	before_filter :layout_container, except: [:contact, :events_sidebar, :update_location]

	def update_location
		location
	end

	def events_sidebar
		@venues = Venue.local(100, location).with_upcoming_events
		@local_events = @venues.collect {|venue| venue.events}.first
		@local_events = @local_events ? @local_events.order(moment: :asc) : nil
	end

	def contact
		@layout_container = "action-panel"
		choose_layout
	end

	def send_contact
		@email = params[:user][:email]
		@message = params[:message]
		ContactTristan.user_email(@email, @message).deliver
	end

	def main
#		@new_tracks = Music.order(created_at: :desc).where(processed: true).limit(5)
#		@active_users = Array.new

		#Determine "active users"
#		User.all.each do |user|
#			if user.musics.exists?
#				if ((1.week.ago)..(DateTime.now)).cover?(user.musics.last.created_at)
#					@active_users << user
#				end
#			end
#		end

		#Local Users
#		@local_users = User.local(100, location)

		#Random Featured Artist
		@featured_user = User.artists.random_user
		choose_layout
	end

	def about
		choose_layout
	end

	def test
	end

	def wow
		choose_layout
	end

	def discover
		#@top_most_played_tracks = Track.most_played
		#@tags = Tag.unique_tags
		choose_layout
	end

	def upload
		choose_layout
	end

	private
	def choose_layout
		respond_to do |format|
			format.html
			format.js { render layout: "events"}
		end
	end
	def layout_container
		@layout_container = "main-body"
	end

end

app/views/static_pages/_welcome.html.erb
<div class="content-block">
	<h3 class="underlined-header">Welcome to DogeRadio!</h3>
	<p><strong>Wow!</strong> - Discover local events from new and upcoming artists.</p>
	<p><strong>Global and Frictionless</strong> - Dogecoin can be accepted anywhere all over the world (and beyond).</p>
	<p><strong>Privacy When You Want It</strong> - Donate anonymously or let artists know you love them.</p>
	<h5>Check out the <strong><%= link_to "status log", "https://docs.google.com/document/d/1WRNBUZ-hMdhQyL7ToAqVf6qHEYQTVkl03blmMPZvKSo/edit?usp=sharing", target: "_blank" %></strong> for development details. And feel free to <strong><%= link_to "contact us", "/contact-us", remote: true %></strong> to provide feedback, ask questions, or if you want to help!</h5>
</div>

app/views/static_pages/about.html.erb
<%= render partial: 'static_pages/welcome' %>

app/views/static_pages/contact.html.erb
<h3 class="underlined-header">Contact Tristan at DogeRadio!</h3>
<%= form_tag '/send_contact', role: "form", remote: true do %>
  <div class="form-group">
    <%= label_tag "user_email", "Your e-mail address" %>
    <%= email_field "user", "email", class: "form-control", placeholder: "Enter your e-mail so we can respond." %>
  </div>
  <div class="form-group">
    <%= label_tag :message, "Your message" %>
    <%= text_area_tag :message, nil, class: "form-control", rows: "3" %>
  <%= submit_tag "Send", class: "btn btn-default btn-block", style: "margin-top:10px" %>
<% end %>

app/views/static_pages/discover.html.erb
<div class="content-block">
	<ul class="nav nav-tabs" id="tabs">
		<li class="tab-item"><%= link_to local_users_path, data: {toggle: "tab", target: "#users"}, remote: true do %>Users<% end %></li>
		<li class="tab-item"><%= link_to top_tracks_path, data: {toggle: "tab", target: "#tracks"}, remote: true do %>Tracks<% end %></li>
		<li class="tab-item"><%= link_to local_events_path, data: {toggle: "tab", target: "#events"}, remote: true do %>Events<% end %></li>
		<li class="tab-item"><%= link_to local_venues_path, data: {toggle: "tab", target: "#venues"}, remote: true do %>Venues<% end %></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane" id="users"></div>
		<div class="tab-pane" id="tracks"></div>
		<div class="tab-pane" id="events"></div>
		<div class="tab-pane" id="venues"></div>
	</div>
</div>

app/views/static_pages/events_sidebar.js.erb
$("#main-sidebar").html("<%=j render partial: 'shared/events_sidebar' %>");

app/views/static_pages/main.html.erb
<%= render partial: 'static_pages/welcome' if !signed_in? %>
<%= render partial: 'users/featured_user', locals: { user:@featured_user } if @featured_user %>

app/views/static_pages/send_contact.js.erb
$("#action-panel").html("<h3 class='alert alert-success'>Your message has been delivered to Tristan@dogeradio.com!</h3>").delay(3000).slideUp();

app/views/static_pages/sidebar.js.erb
$("<%=j render partial: 'shared/sidebar' %>").prependTo($("#main-container")).hide().slideDown(function(){
	refreshTicker();
});
refreshPlayer();

app/views/static_pages/test.html.erb
<h1>Variable:</h1><h4><%= session[:geo_location] %>

app/views/static_pages/topbar.js.erb
$("<%=j render partial: 'shared/topbar' %>").prependTo($("#body-container")).hide().slideDown(function(){
	refreshTicker();
});
refreshPlayer();

app/views/static_pages/update_location.js.erb
<% if @location.city %>
	$("#location_city").html("<%=j @location.city %>");
	<% if (@location.state.length + @location.city.length < 17) && @location.state %>
		$("#location_state").html(", <%=j @location.state %>");
	<% else %>
		$("#location_state").html("");
	<% end %>
<% elsif @location.state %>
	$("#location_city").html("");
	$("#location_state").html("<%=j @location.state %>");
<% else %>
	$("#location_city").html("Where?");
	$("#location_state").html("");
<% end %>

app/views/static_pages/upload.html.erb
<div class="content-block">
	<ul class="nav nav-tabs" id="tabs">
		<li class="tab-item"><%= link_to new_music_path, remote: true, data: {toggle: "tab", target: "#upload-track"}, class:"remote-link" do %>Upload Tracks<% end %></li>
		<li class="tab-item"><%= link_to new_venue_path, class: "remote-link", data: {toggle: "tab", target: "#new-venue"}, remote:true do %>Add a Venue<% end %></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane" id="upload-track"></div>
		<div class="tab-pane" id="new-venue"></div>
	</div>
</div>

app/views/static_pages/wow.html.erb
<div class="content-block">
	<ul class="nav nav-tabs" id="tabs">
		<li class="tab-item"><%= link_to following_path(current_user), data: {toggle: "tab", target: "#users"}, remote: true do %>Users<% end %></li>
		<li class="tab-item"><%= link_to 'javascript:;', data: {toggle: "tab", target: "#tags"}, remote: true do %>Tags<% end %></li>
		<li class="tab-item"><%= link_to favorite_tracks_path(current_user), data: {toggle: "tab", target: "#tracks"}, remote: true do %>Tracks<% end %></li>
		<li class="tab-item"><%= link_to 'javascript:;', data: {toggle: "tab", target: "#venues"}, remote: true do %>Venues<% end %></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane" id="users"></div>
		<div class="tab-pane" id="tags"></div>
		<div class="tab-pane" id="tracks"></div>
		<div class="tab-pane" id="venues"></div>
	</div>
</div>