config/routes.rb
Dogeradio::Application.routes.draw do

  root 'static_pages#main'

  get 'contact-us', to: 'static_pages#contact'
  post 'send_contact', to: 'static_pages#send_contact'
  get 'sidebar', to: 'static_pages#sidebar'
  get 'topbar', to: 'static_pages#topbar'
  get 'events_sidebar', to: 'static_pages#events_sidebar'
  get 'test', to: 'static_pages#test'
  get 'discover', to: 'static_pages#discover'
  get 'wow', to: 'static_pages#wow'
  get 'about', to: 'static_pages#about'
  get 'upload', to: 'static_pages#upload'
  post 'update_location', to: 'static_pages#update_location'
  get 'recent_tips', to: 'transactions#recent'

  post 'guest_charge', to: 'transactions#guest_charge'

  post 'sync_jambase_ids', to: 'venues#sync_jambase_ids'
  post 'search', to: 'search#search'
  get 'search_tracks', to: 'search#tracks'
  get 'search_tags', to: 'search#tags'
  get 'search_users', to: 'search#users'

  get 'local_venues', to: 'venues#local_venues'
  get 'local_events', to: 'events#local_events'
  post 'add_yelp_venues', to: 'venues#add_yelp_venues'
  get 'load_yelp_suggestions', to: "venues#load_yelp_suggestions"

  resources :venues do
    get :events, to: "events#venue_events"
    resources :events, except: [:index, :show, :destroy]
  end

	resources :events, only: [:index, :show, :destroy] do
    resources :user, only: [:new], to: 'events#new_user'
    resources :user, only: [:create], to: 'events#add_user', as: 'add_user'
  end

	resources :playlists, only: [:show] do
		post :sort
		resource :ranks
	end

  resources :tags, only: [:destroy]

  get 'top_tracks', to: "tracks#top_tracks"
	resources :tracks do
		resources :plays
		resources :tags, except: [:destroy]
		get :fond_users
		post :update_player
	end

  resources :musics, only: [:create, :new]

  devise_for :users, controllers: {registrations: "registrations"}

	post 'hold_charge', to: "transactions#hold_charge"
	resources :transactions, only: [:index]

  resources :votes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

	get 'soundcloud', to: 'users#soundcloud_auth'
	get 'soundcloud_callback', to: 'users#soundcloud_callback'
	post 'payout', to: 'users#payout'

  get 'local_users', to: 'users#local_users'
  resources :users, only: [:index]

  scope ':username' do
    post 'verify' => 'users#verify'
    post 'unverify' => 'users#unverify'
		post 'autopay' => 'users#autopay'
		post 'pay' => 'users#pay'
		post 'update_balance' => 'users#update_balance'
		get 'following' => 'users#following'
		get 'followers' => 'users#followers'
		get 'favorite_tracks'=> 'users#favorite_tracks'
	end

  get ':username', to:'users#show', as: :user

end

app/views/shared/_account.html.erb
<p>We can record this transaction and pass your tip of <%= amount %> Doge along to the artist as soon as you send your dogecoin to:</p>
<h3><%= account %></h3>

app/views/shared/_action_panel.html.erb
<div id="action-panel" class="content-block" style="display:none;">
</div>

app/views/shared/_enter_location.html.erb
<%= form_tag events_sidebar_path, class: 'form-inline', role: "form", remote: true, method: :get do %>
	<div class="input-group">
		<%= text_field_tag :location, nil, placeholder: 'Search location', class:"form-control input-md" %>
		<span class="input-group-btn">
			<%= button_tag type: "submit", class: "btn btn-primary btn-md" do %>
			<span class="glyphicon glyphicon-map-marker"></span>
			<% end %>
		</span>
	</div>
<% end %>

app/views/shared/_events_sidebar.html.erb
<input type= "hidden" id="sidebar_status" value="events">
<div class="content-block" id="local-events" style="min-height:100px;">
	<h3 class="underlined-header">Local<small style="float: right; position:relative; top:5px"><span id="location_city"></span><span id="location_state"></span></small></h3>
	<%= render partial: 'shared/enter_location' %>
	<%= render partial: 'events/local_events', locals: {events: @local_events } %>
</div>
<script>
	$(document).ready(function(){
		$.post("/update_location");
	});
</script>

app/views/shared/_favorite.html.erb
<%= form_for current_user.favorites.build(track_id: track.id), remote: true do |f| %>
	<div><%= f.hidden_field :track_id %></div>
	<%= f.submit "wow", class: "btn btn-default btn-xs" %>
<% end %>

app/views/shared/_favorite_form.html.erb
<% unless my_song?(track) %>
	<div class="favorite_form_<%=track.id%>" style="display:inline-block;">
		<% if current_user.favorite?(track) %>
			<%= render partial: 'shared/unfavorite', locals: {track: track} %>
		<% else %>
			<%= render partial: 'shared/favorite', locals: {track: track} %>
		<% end %>
	</div>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for current_user.relationships.build(followed_id: user.id), remote: true do |f| %>
	<div><%= f.hidden_field :followed_id %></div>
	<%= f.submit "so follow", class: "btn btn-default" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(user) %>
	<div id="follow_form_<%=user.id%>" style="position: absolute; right: 10px; top:80px">
		<% if current_user.following?(user) %>
			<%= render partial: 'shared/unfollow', locals: {user: user} %>
		<% else %>
			<%= render partial: 'shared/follow', locals: {user: user} %>
		<% end %>
	</div>
<% end %>

app/views/shared/_invoice.html.erb
<div id="invoiceModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Tip Invoice" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title">How generous!</h3>
			</div>
			<% if user_signed_in? %>
				<div class="modal-body">
					<%= render partial: 'shared/account', locals: {amount: current_user.default_tip_amount, account: current_user.account} %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">No, thank you.</button>
					<%= link_to hold_charge_path(transaction:{track_id: track_id, user_id: payee_id, method: method}), remote: true, method: :post, data:{dismiss: "modal"}, class: "btn btn-success confirm-user-tip" do %>Yes, please!<% end %>
				</div>
			<% else %>
				<div class="modal-body">
					<%= form_for Transaction.new, remote: true, url: guest_charge_path, html: {class: "form-horizontal", role: "form"} do |f|%>
						<%= f.hidden_field :payee_id, value: payee_id %>
						<%= f.hidden_field :track_id, value: track_id %>
						<%= f.hidden_field :method, value: method %>
						<div class="form-group">
							<%= f.label :email, class: "col-sm-2 control-label" %>
							<div class="col-sm-10">
								<%= email_field :transaction, :email, class: "form-control input-lg" %>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :value, "Amount", class: "col-sm-2 control-label" %>
							<div class="col-sm-10">
								<%= f.text_field :value, class: "form-control input-lg" %>
							</div>
						</div>
						<div class="form-group">
							<%= show_simple_captcha %>
						</div>
						<div class="form-group">
							<%= f.submit "Send Thanks!", id: 'tip-button', class: "btn btn-primary btn-block" %>
						</div>
						<div class="alert tip-alert" style="display:none">
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_playlist.html.erb
<ul id="playlist" class="list-group sortable" data-playlist_id="<%=@playlist.id %>" <% if !defined?(hidden).nil? %>style="display:none;"<% end %>>
	<% playlist_counter = 1 %>
	<% @playlist.tracks.each do |track| %>
		<%= render partial: 'tracks/playlist_item', locals: {track: track, playlist_counter: playlist_counter} %>
		<% playlist_counter += 1 %>
	<% end %>
</ul>

app/views/shared/_stats.html.erb
<% @user || = current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_topbar.html.erb
<div class="row" id="topbar">
	<div class="col-sm-12" style="padding:0;">
		<div class="content-block">
			<button type="button" id="maximize-sidebar" class="btn btn-default btn-xs size-button"><span class="glyphicon glyphicon-resize-full"></span></button>
			<div id="player"><%= render partial: "tracks/topplayer", locals: {track: @track, position: @player_position } %></div>
			<%= render partial: 'shared/ticker' %>
			<%= render partial: 'shared/playlist', locals: { hidden: true } %>
		</div>
	</div>
</div>

app/views/shared/_unfavorite.html.erb
<%= form_for current_user.favorites.find_by(track_id: track.id), method: :delete, remote: true do |f| %>
	<%= f.submit "wow", class: "btn btn-xs btn-warning" %>
<% end %>

app/views/shared/_unfollow.html.erb
<%= form_for current_user.relationships.find_by(followed_id: user.id), method: :delete, remote: true do |f| %>
	<%= f.submit "unfollow", class: "btn btn-default" %>
<% end %>