config/routes.rb
Dogeradio::Application.routes.draw do

  root 'static_pages#main'

  get 'contact-us', to: 'static_pages#contact'
  post 'send_contact', to: 'static_pages#send_contact'
  get 'sidebar', to: 'static_pages#sidebar'
  get 'topbar', to: 'static_pages#topbar'
  get 'events_sidebar', to: 'static_pages#events_sidebar'
  get 'test', to: 'static_pages#test'
  get 'discover', to: 'static_pages#discover'
  get 'wow', to: 'static_pages#wow'
  get 'about', to: 'static_pages#about'
  get 'upload', to: 'static_pages#upload'
  post 'update_location', to: 'static_pages#update_location'
  get 'recent_tips', to: 'transactions#recent'

  post 'guest_charge', to: 'transactions#guest_charge'

  post 'sync_jambase_ids', to: 'venues#sync_jambase_ids'
  post 'search', to: 'search#search'
  get 'search_tracks', to: 'search#tracks'
  get 'search_tags', to: 'search#tags'
  get 'search_users', to: 'search#users'

  get 'local_venues', to: 'venues#local_venues'
  get 'local_events', to: 'events#local_events'
  post 'add_yelp_venues', to: 'venues#add_yelp_venues'
  get 'load_yelp_suggestions', to: "venues#load_yelp_suggestions"

  resources :venues do
    get :events, to: "events#venue_events"
    resources :events, except: [:index, :show, :destroy]
  end

	resources :events, only: [:index, :show, :destroy] do
    resources :user, only: [:new], to: 'events#new_user'
    resources :user, only: [:create], to: 'events#add_user', as: 'add_user'
  end

	resources :playlists, only: [:show] do
		post :sort
		resource :ranks
	end

  resources :tags, only: [:destroy]

  get 'top_tracks', to: "tracks#top_tracks"
	resources :tracks do
		resources :plays
		resources :tags, except: [:destroy]
		get :fond_users
		post :update_player
	end

  resources :musics, only: [:create, :new]

  devise_for :users, controllers: {registrations: "registrations"}

	post 'hold_charge', to: "transactions#hold_charge"
	resources :transactions, only: [:index]

  resources :votes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

	get 'soundcloud', to: 'users#soundcloud_auth'
	get 'soundcloud_callback', to: 'users#soundcloud_callback'
	post 'payout', to: 'users#payout'

  get 'local_users', to: 'users#local_users'
  resources :users, only: [:index]

  scope ':username' do
    post 'verify' => 'users#verify'
    post 'unverify' => 'users#unverify'
		post 'autopay' => 'users#autopay'
		post 'pay' => 'users#pay'
		post 'update_balance' => 'users#update_balance'
		get 'following' => 'users#following'
		get 'followers' => 'users#followers'
		get 'favorite_tracks'=> 'users#favorite_tracks'
	end

  get ':username', to:'users#show', as: :user

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id          :integer          not null, primary key
#  object_id   :integer
#  category    :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  type        :string(255)
#

class Tag < ActiveRecord::Base
  	belongs_to :track, foreign_key: :object_id
  	belongs_to :venue, foreign_key: :object_id
  	belongs_to :user, foreign_key: :object_id
	validates :object_id, presence: true
	validates :category, :description, presence: true

	searchkick text_start: ['description'], index_name: 'tags_index'
	has_many :votes, dependent: :destroy

	include CI_Find
	include CI_Find_First

	scope :track_tags, -> { where(what: "track") }
	scope :unique_track_tags, -> {select(:category, :description).uniq}
	scope :by_votes, -> { joins(:votes) }

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:search, :show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:update, :edit, :create, :destroy, :new]
  before_filter :layout_container, only: [:new]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
		@track = Track.find(params[:track_id])
    @tag_categories = YAML.load_file("#{Rails.root}/config/track_categories.yml")
    choose_layout
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
		@track = Track.find(params[:track_id])
    @tag = @track.tags.build(tag_params)
    @tag.what="track"
    @tag.save
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:category, :description)
    end

    def layout_container
      @layout_container = "action-panel"
    end

    def choose_layout
      respond_to do |format|
        format.html
        format.js { render layout: "events"}
      end
    end
end

app/views/tags/_delete_form.html.erb
<div style="display:inline-block;">
	<%= button_to tag_path(tag), method: :delete, remote: true, class: "btn btn-xs delete tag-"+tag.category do %>
		<span class="glyphicon glyphicon-remove"></span>
	<% end %>
</div>

app/views/tags/_form.html.erb
<%= form_for [@track, @tag], html: {class: "form-inline", role: "form"}, remote: true do |f| %>
  <div class="form-group">
    <%= f.select :category, options_for_select(@tag_categories), {}, class: "form-control input-sm tag-form", id: "tag-options" %>
  </div>
  <div class="form-group">
    <%= f.text_field :description, class: "form-control input-sm", placeholder: "Description" %>
  </div>
  <%= f.submit 'Add Tag', class: "btn btn-primary" %>
<% end %>

app/views/tags/_show_tags.html.erb
<% vote ||= false %>
<% track.tags.each do |tag| %>
	<% if vote==false %>
		<%= render partial: 'tags/tag', locals: {tag: tag} %>
	<% else %>
		<%= render partial: "tags/tag_vote", locals: {tag: tag} %>
	<% end %>
<% end %>

app/views/tags/_tag.html.erb
<button type="button" data-category="<%= tag.category %>" data-description="<%= tag.description %>" class="tag-<%=tag.id%> remote-link btn tag btn-xs tag-<%= tag.category %>"><%= tag.description %></button>

app/views/tags/_tag_vote.html.erb
<span class="btn-group tag-<%=tag.id%>">
	<button type="button" data-category="<%= tag.category %>" data-description="<%= tag.description %>" class="btn tag btn-xs tag-<%= tag.category %>">
		<%= tag.description %>
	</button>
	<%= render partial: 'tags/vote_form', locals: {tag: tag} if signed_in? %>
	<%= render partial: 'tags/delete_form', locals: {tag: tag} if current_user.try(:admin?) %>
</span>

app/views/tags/_vote_down.html.erb
<%= button_to vote_path(tag.id), method: :delete, remote: true, class: "btn btn-xs vote tag-"+tag.category, style:"color: #ba9133" do %>
	<span class="glyphicon glyphicon-thumbs-up"></span>
<% end %>

app/views/tags/_vote_form.html.erb
<div id="vote_form_<%=tag.id%>" style="display:inline-block;">
	<% if current_user.vote?(tag) %>
		<%= render partial: 'tags/vote_down', locals: {tag: tag} %>
	<% else %>
		<%= render partial: 'tags/vote_up', locals: {tag: tag} %>
	<% end %>
</div>

app/views/tags/_vote_up.html.erb
<%= button_to votes_path(tag_id: tag.id), remote: true, class: "btn btn-xs vote tag-"+tag.category do %>
	<span class="glyphicon glyphicon-thumbs-up"></span>
<% end %>

app/views/tags/create.js.erb
$('#action-panel').slideUp('slow');
var player_track = $("#player-heading").data('track_id');
if (player_track == <%=@track.id%>) {
	$("#player-tags").html("<%= j render partial: 'show_tags', locals: {track: @track} %><button type='button' id='add-tag' class='btn btn-xs btn-default'><span class='glyphicon glyphicon-plus'></span><span class='glyphicon glyphicon-tag'></span></button>");
}

app/views/tags/destroy.js.erb
$('.tag-<%= params[:id]%>').slideUp();

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th>Music</th>
      <th>Category</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.music %></td>
        <td><%= tag.category %></td>
        <td><%= tag.description %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h3 class="underlined-header"><strong><%= @track.name %></strong> <small><%= @track.user.username %></small></h3>
<%= render partial: 'tags/form' %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Music:</strong>
  <%= @tag.music %>
</p>

<p>
  <strong>Category:</strong>
  <%= @tag.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tag.description %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>