config/routes.rb
Dogeradio::Application.routes.draw do

  root 'static_pages#main'

  get 'contact-us', to: 'static_pages#contact'
  post 'send_contact', to: 'static_pages#send_contact'
  get 'sidebar', to: 'static_pages#sidebar'
  get 'topbar', to: 'static_pages#topbar'
  get 'events_sidebar', to: 'static_pages#events_sidebar'
  get 'test', to: 'static_pages#test'
  get 'discover', to: 'static_pages#discover'
  get 'wow', to: 'static_pages#wow'
  get 'about', to: 'static_pages#about'
  get 'upload', to: 'static_pages#upload'
  post 'update_location', to: 'static_pages#update_location'
  get 'recent_tips', to: 'transactions#recent'

  post 'guest_charge', to: 'transactions#guest_charge'

  post 'sync_jambase_ids', to: 'venues#sync_jambase_ids'
  post 'search', to: 'search#search'
  get 'search_tracks', to: 'search#tracks'
  get 'search_tags', to: 'search#tags'
  get 'search_users', to: 'search#users'

  get 'local_venues', to: 'venues#local_venues'
  get 'local_events', to: 'events#local_events'
  post 'add_yelp_venues', to: 'venues#add_yelp_venues'
  get 'load_yelp_suggestions', to: "venues#load_yelp_suggestions"

  resources :venues do
    get :events, to: "events#venue_events"
    resources :events, except: [:index, :show, :destroy]
  end

	resources :events, only: [:index, :show, :destroy] do
    resources :user, only: [:new], to: 'events#new_user'
    resources :user, only: [:create], to: 'events#add_user', as: 'add_user'
  end

	resources :playlists, only: [:show] do
		post :sort
		resource :ranks
	end

  resources :tags, only: [:destroy]

  get 'top_tracks', to: "tracks#top_tracks"
	resources :tracks do
		resources :plays
		resources :tags, except: [:destroy]
		get :fond_users
		post :update_player
	end

  resources :musics, only: [:create, :new]

  devise_for :users, controllers: {registrations: "registrations"}

	post 'hold_charge', to: "transactions#hold_charge"
	resources :transactions, only: [:index]

  resources :votes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

	get 'soundcloud', to: 'users#soundcloud_auth'
	get 'soundcloud_callback', to: 'users#soundcloud_callback'
	post 'payout', to: 'users#payout'

  get 'local_users', to: 'users#local_users'
  resources :users, only: [:index]

  scope ':username' do
    post 'verify' => 'users#verify'
    post 'unverify' => 'users#unverify'
		post 'autopay' => 'users#autopay'
		post 'pay' => 'users#pay'
		post 'update_balance' => 'users#update_balance'
		get 'following' => 'users#following'
		get 'followers' => 'users#followers'
		get 'favorite_tracks'=> 'users#favorite_tracks'
	end

  get ':username', to:'users#show', as: :user

end

app/models/music.rb
# == Schema Information
#
# Table name: musics
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  user_id             :integer          not null
#  direct_upload_url   :string(255)      not null
#  upload_file_name    :string(255)
#  upload_content_type :string(255)
#  upload_file_size    :integer
#  upload_updated_at   :datetime
#  processed           :boolean          default(FALSE), not null
#  created_at          :datetime
#  updated_at          :datetime
#

class Music < ActiveRecord::Base

	# Environment-specific direct upload url verifier screens for malicious posted upload locations.
	DIRECT_UPLOAD_URL_FORMAT = %r{\Ahttps:\/\/dogeradio#{!Rails.env.production? ? "\\-#{Rails.env}" : ''}\.s3\.amazonaws\.com\/(?<path>uploads\/.+\/(?<filename>.+))\z}.freeze
	UPLOAD_URL_FORMAT = %r{\Ahttps:\/\/s3\.amazonaws\.com\/myapp#{!Rails.env.production? ? "\\-#{Rails.env}" : ''}\/(?<path>uploads\/.+\/(?<filename>.+))\z}.freeze

	include CI_Find
	include CI_Find_First

	belongs_to :user
	has_attached_file :upload
	validates_attachment_content_type :upload, content_type: ['audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio']
	#validates_attachment_file_name :upload, matches: [/mp3\Z/, /mpeg\Z/, /ogg\Z/]
	#do_not_validate_attachment_file_type :upload

	validates :direct_upload_url, presence: true, format: { with: DIRECT_UPLOAD_URL_FORMAT }

  before_create :set_upload_attributes
  after_create :queue_processing

  # Store an unescaped version of the escaped URL that Amazon returns from direct upload.
	def direct_upload_url=(escaped_url)
		write_attribute(:direct_upload_url, (CGI.unescape(escaped_url) rescue nil))
  end

  # Final upload processing step
  def self.transfer_and_cleanup(id)
	  music = Music.find(id)
		direct_upload_url_data = DIRECT_UPLOAD_URL_FORMAT.match(music.direct_upload_url)
		clean_direct_upload_url = direct_upload_url_data[:filename].gsub(/[^0-9A-Za-z.\-]/, '_')

	  s3 = AWS::S3.new

    paperclip_file_path = "musics/uploads/#{id}/original/#{clean_direct_upload_url}"
    s3.buckets[Rails.configuration.aws[:bucket]].objects[paperclip_file_path].copy_from(direct_upload_url_data[:path])

	  music.processed = true
    music.save

		user = music.user

		user.tracks.create(name:music.name, url: music.upload.url, source: "upload")

		s3.buckets[Rails.configuration.aws[:bucket]].objects[direct_upload_url_data[:path]].delete
	end

	def associated_track
		Track.where(url:self.upload.url).first
	end

	protected

	# Set attachment attributes from the direct upload
  # @note Retry logic handles S3 "eventual consistency" lag.
  def set_upload_attributes
	  tries ||= 5
    direct_upload_url_data = DIRECT_UPLOAD_URL_FORMAT.match(direct_upload_url)
    s3 = AWS::S3.new
    direct_upload_head = s3.buckets[Rails.configuration.aws[:bucket]].objects[direct_upload_url_data[:path]].head

    self.upload_file_name     = direct_upload_url_data[:filename]
		self.upload_file_size     = direct_upload_head.content_length
    self.upload_content_type  = direct_upload_head.content_type
    self.upload_updated_at    = direct_upload_head.last_modified
  rescue AWS::S3::Errors::NoSuchKey => e
		tries -= 1
    if tries > 0
	    sleep(3)
 	    retry
	  else
	    false
	  end
	end

	# Queue file processing
  def queue_processing
	  Music.transfer_and_cleanup(id)
  end

#	def transliterate(str)
#		s = Iconv.iconv('ascii//ignore//translit', 'utf-8', str).to_s
#		s.downcase!
#		s.gsub!(/[^A-Za-z0-9]+/, ' ')
#		s.gsub!(/'/, '')
#		s.strip!
#		s.gsub!(/\ +/, '-')
#		return s
#	end

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  before_filter :layout_container, only: [:new]

	# POST /musics
  # POST /musics.json
  def create
    @music = current_user.uploaded_tracks.new(music_params)
		@music.name = params[:filename]
		@music.save
		@track = @music.associated_track
  end

  def new
    choose_layout
  end

	# GET /musics/1
	# GET /musics/1.json
	def show
	end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
	def destroy
    @music.destroy
		flash[:notice] = "Song has been deleted."
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:name, :user_id, :upload, :direct_upload_url, :upload_file_name, :processed)
    end

    def layout_container
      @layout_container = "upload-track"
    end 

    def choose_layout
      respond_to do |format|
        format.html
        format.js { render layout: "events"}
      end 
    end
end

app/views/musics/_form.html.erb
<div class="form-group">
	<%= s3_uploader_form callback_url: musics_url,
		id: "s3_uploader",
		callback_param: "music[direct_upload_url]",
		expiration: 24.hours.from_now.utc.iso8601 do %>
		<%= file_field_tag :file, multiple: true, class: "form-control" %>
	<% end %>

	<div id="uploads_container"></div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#s3_uploader').S3Uploader({
			remove_completed_progress_bar: false,
			progress_bar_target: $('#uploads_container')
		});

		$('#s3_uploader').bind('s3_upload_failed', function(e, content) {
			return alert(content.filename + " failed to upload.");
		});
	});
</script>

<script id="template-upload" type="text/x-tmpl">
	<div id="upload_{%=o.unique_id%}" class="upload">
		<div class='form-holder'><h5>{%=o.name%}</h5></div>
		<div class="progress progress-striped active"><div class="bar progress-bar" role="progressbar" style="width: 0%"></div></div>
	</div>
</script>

app/views/musics/create.js.erb
<% if @music.persisted? %>
	$('#upload_<%=params[:unique_id]%> div.progress').removeClass('active progress-striped');
	$('#upload_<%=params[:unique_id]%> div.progress div.progress-bar').addClass('progress-bar-success');
	$('#upload_<%=params[:unique_id]%> div.form-holder').html("<%= j render partial: 'tracks/rename', locals: {track: @track, placeholder: params[:filename]} %>");
<% else %>
	$('#upload_<%=params[:unique_id]%> div.progress').removeClass('active progress-striped');
	$('#upload_<%=params[:unique_id]%> div.progress div.progress-bar').addClass('progress-bar-danger');
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/new.html.erb
<%= render 'musics/form' %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @music.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @music.user %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>